server:
  port: 10086 # server port
spring:
  application:
    name: eurekaserver # eureka service name
eureka:
  client:
    service-url:  # eureka address
      defaultZone: http://127.0.0.1:10086/eureka